<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="LAPTOP-VRNPC7JT" failures="1" tests="1" name="Default test" time="8.434" errors="0" timestamp="2025-09-20T20:45:06 IST">
  <testcase classname="com.testExecution.TestExecution" name="validateCartNotIncreases" time="5.38">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Cart count increased after invalid action did not expect [0] but found [0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Cart count increased after invalid action did not expect [0] but found [0]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.PageExecution.AddToCartTest.cartNotIncrease(AddToCartTest.java:64)
at com.testExecution.TestExecution.validateCartNotIncreases(TestExecution.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCartNotIncreases -->
  <testcase classname="com.testExecution.TestExecution" name="searchUnwantedProductList" time="0.0">
    <ignored/>
  </testcase> <!-- searchUnwantedProductList -->
  <testcase classname="com.testExecution.TestExecution" name="addToCartValidate" time="0.0">
    <ignored/>
  </testcase> <!-- addToCartValidate -->
  <testcase classname="com.testExecution.TestExecution" name="invalidLogin" time="0.0">
    <ignored/>
  </testcase> <!-- invalidLogin -->
  <testcase classname="com.testExecution.TestExecution" name="searchProductList" time="0.0">
    <ignored/>
  </testcase> <!-- searchProductList -->
  <testcase classname="com.testExecution.TestExecution" name="loginApp" time="0.0">
    <ignored/>
  </testcase> <!-- loginApp -->
</testsuite> <!-- Default test -->
